### ISSUE TITLE
neovim-nightly-bin: pkgver() causes the warning during upgrade

### ISSUE THREAD

**Issue by figuld** [eclairevoyant/aur-packages#10]
Basically, see my last comment in AUR.

In short, the `pkgver()` output has a flaw: pacman most of the time doesn't recognize that it's greater version, than the previous one, so it doesn't update the package by default, requiring manually typing `paru -Syu neovim-nightly-bin`.

Hmm, so maybe there's a way to change the version string a little bit to include the count number? Like `0.10.0+dev+COMMIT` -> `0.10.0.dev.rCOUNT.COMMIT`

**Comment by figuld** [comment]
@eclairevoyant, @zeertzjq, sorry if the pings bothered you, just making sure, you got notified about this issue.

**Comment by zeertzjq** [comment]
I don't think that's the case. Is `pkgver()` called if you don't install the package explicitly?

**Comment by figuld** [comment]
@zeertzjq, I don't really understand, could you be more specific? Are you talking about just building the package?
Anyways, I use chaotic-aur which, I guess, uses the `pkgver()`:
```
[2023-09-13T14:50:21+0300] [ALPM] downgraded neovim-nightly-bin (0.10.0+dev+4258f4d-1 -> 0.10.0+dev+aab06ed-1)
[2023-09-15T20:22:26+0300] [ALPM] downgraded neovim-nightly-bin (0.10.0+dev+aab06ed-1 -> 0.10.0+dev+a6e74c1-1)
[2023-09-18T01:07:49+0300] [ALPM] upgraded neovim-nightly-bin (0.10.0+dev+a6e74c1-1 -> 0.10.0+dev+be10d65-1)
...
[2023-09-21T01:49:55+0300] [ALPM] upgraded neovim-nightly-bin (0.10.0+dev+9cadbf1-1 -> 0.10.0+dev+6405fa4-1)
[2023-09-22T01:43:43+0300] [ALPM] downgraded neovim-nightly-bin (0.10.0+dev+6405fa4-1 -> 0.10.0+dev+c4f4c7a-1)
...
```

Hmm, now I think it's the neovim itself to blame, the version just changed out of nowhere:
```
...
[2023-09-10T13:52:06+0300] [ALPM] upgraded neovim-nightly-bin (0.10.0+dev+1031+gc431d820e-1 -> 0.10.0+dev+1055+gb7734c4ec-1)
[2023-09-12T17:48:27+0300] [ALPM] upgraded neovim-nightly-bin (0.10.0+dev+1055+gb7734c4ec-1 -> 0.10.0+dev+4258f4d-1)
```

**Comment by eclairevoyant** [comment]
I'm not really sure what I can do with a binary package. The pkgver comes from neovim.

**Comment by zeertzjq** [comment]
Hmm, it seems to be broken for several months.

**Comment by eclairevoyant** [comment]
Maybe I can try to insert some kind of date or monotonically increasing value...I'll have to think about it.

**Comment by zeertzjq** [comment]
Should be fixed now.

**Comment by figuld** [comment]
@zeertzjq, I found that [commit 5acd850](https://github.com/neovim/neovim/commit/5acd8501177eded74d94ab8f307a18ae0a4d334d) broke it, thanks for reverting it.

I will wait for a new hourly build on chaotic-aur.

**Comment by figuld** [comment]
@eclairevoyant, it works now:
```
[2023-12-01T01:24:38+0300] [ALPM] upgraded neovim-nightly-bin (0.10.0+dev+64b53b7-1 -> 0.10.0+dev+1720+g52d738826-1)
```

Also, [the package somehow prevented the hourly build](https://github.com/chaotic-aur/packages/issues/2343#issuecomment-1834583569).

Btw, one nitpick, I think it would be better to update the AUR version one time `0.9.0`* -> `0.10.0`* to decrease the chance of someone flagging the package out of date.

**Comment by zeertzjq** [comment]
`v0.10.0.r` is larger than `v0.10.0` release version, so it will cause pacman to consider v0.10.0 release to be older than v0.10.0 prerelease.

**Comment by eclairevoyant** [comment]
No, letters are "less than" numbers.

**Comment by zeertzjq** [comment]
But they are larger than the end of the string, right?

**Comment by xiota** [comment]
The problem with version string comparison are the non-alphanumeric characters.
```bash
$ vercmp 0.10.0.dev 0.10.0
1

$ vercmp 0.10.0+dev 0.10.0
1

$ vercmp 0.10.0dev 0.10.0
-1
```

Since these are nightlies, I'd suggest using the date, revision, and hash for the version, like `2023.11.30.r1720.g52d738826`:
```
pkgver() {
  local _pkgver=$(./nvim-linux64/bin/nvim --version)
  local _revision=(cut -d'+' -f 3 <<< "$_pkgver")
  local _hash=(sed -E 's&^.*g([0-9a-f]+)$&\1&' <<< "$_pkgver")
  printf '%s.r%s.g%s' "$_date" "$_revision" "$_hash"
}
```
The solution to the file name / version mismatch issue is to put the correct date from the servers into an extra variable (`$_date`) that is used in the `source` array and `pkgver()` function.  This cannot be done inside `prepare()` or `pkgver()` because the download occurs before they're run.
```bash
_response=$(
  curl -ISsf "https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz" \
    | grep '^location:' | sed -E 's&^location: &&' | strings
)
_response=$(
  curl -ISsf "$_response" | grep '^last-modified:' | sed -E 's&^last-modified: &&' | strings
)
_date=$(date "+%Y.%m.%d" -d "$_response")
```

Note: The `date` command above may not work.  Adding `date` to the `makedepends` array wouldn't help because the extra code has to run before any depends are downloaded and installed.  The date for the current nightly looks like `Thu, 30 Nov 2023 23:09:19 GMT`.  According to online search, this is printed as-is from the server.  So the date could be converted with a bash function.
