### ISSUE TITLE
neovim-git: fix issues mentioned in the aur comments

### ISSUE THREAD

**Issue by figuld** [eclairevoyant/aur-packages#4]
@eclairevoyant, please read and address the 2 recent comments in the AUR.

**Comment by zeertzjq** [comment]
@REmerald Changing version to `0.10.0.*` will cause pacman to treat it as newer than v0.10.0.

And as mentioned in <https://wiki.archlinux.org/title/VCS_package_guidelines#VCS_sources> and <https://bugs.archlinux.org/task/34677>, `makepkg` does not support `--depth=1`.

**Comment by eclairevoyant** [comment]
@REmerald read https://wiki.archlinux.org/title/Arch_User_Repository#Flagging_packages_out-of-date and https://bugs.archlinux.org/task/34677
