### ISSUE TITLE
Astian has emptied source = git+https://gitlab.com/midori-web/midori-desktop.git

### ISSUE THREAD

**Issue by lsteeger** [eclairevoyant/aur-packages#5]
source = git+https://gitlab.com/midori-web/midori-desktop.git

No longer contains any source code.

**Comment by eclairevoyant** [comment]
Then feel free to file a deletion request.

**Comment by lsteeger** [comment]
Ok. Deletion request was submitted at [AUR](https://aur.archlinux.org/pkgbase/midori-git/).
